[package]
name = "rtsp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4.20"
openh264 = "0.4.2"
pretty_env_logger = "0.5.0"
url = "2.4.0"

[dependencies.tokio]
version = "1"
features = ["full"]
