[package]
name = "simple"
version = "0.1.0"
edition = "2021"

[dependencies]
rtsp-rtp-rs= { path="../../" }
anyhow = "1.0.74"
tokio = "1.31.0"
log = "0.4.20"
pretty_env_logger = "0.5.0"
sdl2 = "0.35.2"
